version: '3.8'

services:
  s3ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4713:3000"
    environment:
      - NODE_ENV=production
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      # Mount for development hot reload (optional)
      - ./public:/app/public:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  s3ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4713:4713"
    environment:
      - NODE_ENV=development
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev